### ISSUE TITLE
请增加 “任务重复” 提醒

### ISSUE THREAD

**Issue by sanmaodo** [alexhua/Aria2-Explorer#101]
目前，如果重复添加相同的磁力链接，实际是不会被添加，并且正在下载的计数器也不会变，但通知仍然显示 “aria2已开始下载”，虽无大碍，但很不直观。当下载的任务比较多时，容易搞不清状况。

希望能把通知改成：
 “任务已存在，正在下载  [完成度]”
 “任务已存在，正在等待  [完成度]”     -->  弹窗：“是否开始下载”
 “任务已存在，已完成”
 “任务已存在，已停止      [完成度]”     -->  弹窗：“是否开始下载”

一个小建议，请作者参考，感谢提供这么好的扩展！

**Comment by alexhua** [comment]
挺好的建议，不过开销有点大，每次添加任务前需要向Aria2 Server做三次查询，先留个记录吧。

**Comment by alexhua** [comment]
2.0版加了`任务状态通知`，打开后，重复的任务会直接收到下载完成通知。
