### ISSUE TITLE
Lost previous configuration (the download path)

### ISSUE THREAD

**Issue by GuShaocheng** [alexhua/Aria2-Explorer#115]
Here I am reporting a "bug" or an issue in the blow environment. The previous configuration was lost when rebooting the computer, especially the download path. The download path will automatically change from my setting to the root directory(/).

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Browser edge
 - Version 109.0.1518.52

**Additional context**
ariac2 was configured in rc.local file.

**Comment by alexhua** [comment]
Can not get detail from your description.
1. Which configuration was lost, `your aria2c configure` , `aria2 extension options configuration` or `AriaNG configuration`?
2. Where did you configure you download path?

**Comment by alexhua** [comment]
Close for no further information.
