### ISSUE TITLE
配置了多个aria2实例时，地址栏的检测aria2状态的图标只会显示第一个实例的状态和正在下载数

### ISSUE THREAD

**Issue by nukewarrior** [alexhua/Aria2-Explorer#123]
**Describe the bug**
配置了多个aria2实例时，地址栏的检测aria2状态的图标只会显示第一个实例的状态和正在下载数

<img width="980" alt="image" src="https://user-images.githubusercontent.com/10683831/227764493-63bc8746-a930-4e49-85e2-fed74f0d071e.png">
<img width="206" alt="image" src="https://user-images.githubusercontent.com/10683831/227764508-a65dd771-80aa-47b8-bd82-19c97905706d.png">
其实此时第二个SNAIL实例中是有正在下载的任务的。
<img width="551" alt="image" src="https://user-images.githubusercontent.com/10683831/227764552-ea86ab4c-1ce9-47d4-a431-08503a917118.png">
请问能否让这个检测功能，聚合多个实例的状态，整合多个实例的下载数并显示，谢谢🙏

**Comment by alexhua** [comment]
显示空间有限，一次显示多个实例的状态会有点凌乱，考虑以后加上一个更方便的RPC切换功能。
现在可以通过在`URL Patterns`里填入`*`来切换默认RPC Server。

**Comment by alexhua** [comment]
> 能聚合显示所有实例的下载总数就好了，这样也不额外占地方😊

明白了，是个好提议，我考虑下怎搞。

**Comment by aixia715** [comment]
同样需求，顶一个

**Comment by RoyLi-Pvt** [comment]
> 显示空间有限，一次显示多个实例的状态会有点凌乱，考虑以后加上一个更方便的RPC切换功能。 现在可以通过在`URL Patterns`里填入`*`来切换默认RPC Server。

强烈支持RPC切换

**Comment by alexhua** [comment]
> 强烈支持RPC切换

这个功能已经做好了 ed6d2a060d587f7c7575300af02e0fb75a262040

**Comment by miRemid** [comment]
没有用啊，在扩展图标上面切换了默认rpc，但是还是只会接入第一个地址
