### ISSUE TITLE
下载路径后保存时自动被添加反斜杠  \，导致下载地址错误 （RPC download Location was auto-added a wrong backslash, leading a in-correct download location）

### ISSUE THREAD

**Issue by wxg1015** [alexhua/Aria2-Explorer#124]
新版这点是不是不正常····下载似乎也没下到填写的目录里

**Additional context**

**Comment by alexhua** [comment]
新版会根据系统自动补全路径，Windows下是没问题的。
提供下你的OS信息

**Comment by wxg1015** [comment]
> 新版会根据系统自动补全路径，Windows下是没问题的。
> 提供下你的OS信息和RPC配置信息

![IMG_20230331_175345.jpg](https://user-images.githubusercontent.com/44153358/229088456-a43d7f19-b53e-4027-8146-6b4729ac3bc5.jpg)

![IMG_20230331_175330.jpg](https://user-images.githubusercontent.com/44153358/229088501-793f5106-35bf-489c-8b42-93c1860fd42d.jpg)

浏览器是win10  edge     aria2是群晖docker     我填的路径是/book  结果 保存后直接变  /book\  然后下载任务时也是这个路径   我去book目录下没找到文件

**Comment by wxg1015** [comment]
![IMG_20230331_175933.jpg](https://user-images.githubusercontent.com/44153358/229089699-8b9a6423-0be8-4460-a484-948527f8cf63.jpg)

果然 给我创建了个目录.....

**Comment by alexhua** [comment]
明白了， 我是根据本地OS判断的自动补全，确实会有问题。😂
这个问题还挺棘手，感谢反馈。

**Comment by alexhua** [comment]
> 新版这点是不是不正常····下载似乎也没下到填写的目录里

先提供一个临时解决方案：
1. 打开选项配置页面
2. 按F12，切换到Console
3. 在Console中输入并执行以下代码，可以删掉`Location`最后的`\`
```js
chrome.storage.local.get().then((configs) => {
    for (rpc of configs.rpcList) {
        length = rpc.location.length;
        rpc.location = rpc.location.slice(0, -1);
    }    
    chrome.storage.local.set(configs);
    console.log(configs)
})
```

如果有效请反馈以下，谢谢。

**Comment by alexhua** [comment]
Temporary solution:
1. Open extension options page
2. Press F12 to open Devtool, switch to `Console`
3.  Input and run JS code below:
```js
chrome.storage.local.get().then((configs) => {
    for (rpc of configs.rpcList) {
        length = rpc.location.length;
        rpc.location = rpc.location.slice(0, -1);
    }    
    chrome.storage.local.set(configs);
    console.log(configs)
})
```

**Comment by wxg1015** [comment]
> > 新版这点是不是不正常····下载似乎也没下到填写的目录里
> 
> 先提供一个临时解决方案：
> 1. 打开扩展选项配置页面
> 2. 按F12，切换到Console
> 3. 在Console中输入并执行以下代码，可以删掉`Location`最后的`\`
> ```js
> chrome.storage.local.get().then((configs) => {
>     for (rpc of configs.rpcList) {
>         rpc.location = rpc.location.slice(0, -1);
>     }    
>     chrome.storage.local.set(configs);
>     console.log(configs)
> })
> ```
> 
> 如果有效请反馈一下，谢谢。

好的  回家我试试    哦对了  还有一个问题  就是 我是添加的同一个aria2指定的10个路径   然后我进ariang 就看到 添加了10个 aria2的连接   我记得老版只会有一个？     是不是应该同一aria2只添加一个？

**Comment by alexhua** [comment]
> 好的 回家我试试 哦对了 还有一个问题 就是 我是添加的同一个aria2指定的10个路径 然后我进ariang 就看到 添加了10个 aria2的连接 我记得老版只会有一个？ 是不是应该同一aria2只添加一个？

这个确实需要优化

**Comment by wxg1015** [comment]
> > 新版这点是不是不正常····下载似乎也没下到填写的目录里
> 
> 先提供一个临时解决方案：
> 
> 1. 打开扩展选项配置页面
> 2. 按F12，切换到Console
> 3. 在Console中输入并执行以下代码，可以删掉`Location`最后的`\`
> 
> ```js
> chrome.storage.local.get().then((configs) => {
>     for (rpc of configs.rpcList) {
>         rpc.location = rpc.location.slice(0, -1);
>     }    
>     chrome.storage.local.set(configs);
>     console.log(configs)
> })
> ```
> 
> 如果有效请反馈一下，谢谢。

有效   且会自动保存   但是不能自己再去点网页保存    否则又会加回来

**Comment by alexhua** [comment]
> 动保存 但是不能自己再去点网页保存 否则又会加回

这个只能等下个版本修正了

**Comment by alexhua** [comment]
> 加了10个 aria2的连接 我记得老版只会有一个？ 是不是应该同一aria2只添加一个？

已改进 be271362e0028a809d4d560c0d8ee6b22c6ccac6

**Comment by wxg1015** [comment]
不过话说为啥要加斜杠呢  我记得老版是不加斜杠/的   加不加的有什么区别吗  aria2默认的/dowbloads路径似乎也是没斜杠的

**Comment by alexhua** [comment]
> 不过话说为啥要加斜杠呢 我记得老版是不加斜杠/的 加不加的有什么区别吗 aria2默认的/dowbloads路径似乎也是没斜杠的

用就完事了，普通用户不需要关心为什么。
