### ISSUE TITLE
chrome 的aria2插件始终不能连上服务

### ISSUE THREAD

**Issue by charley008** [alexhua/Aria2-Explorer#125]
**Describe the bug**
chrome的插件Aria2 Explorer 始终连不上我的服务端，chrome用的版本 111.0.5563.147（正式版本） （64 位）
aria2是我在家里nas部署的，通过ipv6来建立连接。
我的操作系统是windows11 ，同样的情况下，用EDGE浏览器 安装的Aria2 Explorer 就能正常连上。

**Screenshots**
![chrome](https://user-images.githubusercontent.com/24822683/229139534-6e278402-b898-4ce6-84ba-0f82e9444afe.png)

![edge](https://user-images.githubusercontent.com/24822683/229139553-192275af-201e-41a5-b3e6-ade59ab07ceb.png)

![chrome-f12](https://user-images.githubusercontent.com/24822683/229139569-1f6d9d2a-8fec-41bd-933a-0c4213a2451b.png)
**Desktop (please complete the following information):**
 - OS: [WINDOWS11 22H2]
 - Browser [chrome,EDGE]
 - Version [chrome 111.0.5563.147] [edge 111.0.1661.54]
Aria2 Explorer 2.0.0

**Additional context**
其他客户端都正正常连接，就是chrome 一直连不上

**Comment by alexhua** [comment]
Chrome和Edge现在代码完全一样，Edge能连上说明代码没问题。
你这个问题挺蹊跷的，是不是Chrome没有解析到ipv6地址，或者是别的网络设置的问题？

**Comment by charley008** [comment]
我把chrome的 使用安全 DNS 都关掉了还是不行。估计是个例

**Comment by charley008** [comment]
![chrome](https://user-images.githubusercontent.com/24822683/229188882-0326370d-470d-4284-8196-97638225724a.png)
![edge](https://user-images.githubusercontent.com/24822683/229188897-7bc29fa8-5e6f-4f0e-b5e8-df5116d2cab3.png)

**Comment by alexhua** [comment]
你上面截图有个host没抹掉，我先给你隐藏了。
我试着在Chrome里连了一下你的NAS，是可以连上的，因为没有密码只提示了认证错误。
所以我怀疑还是网络环境或者Chrome设置的问题。
这个issue我先关了，有问题可以继续讨论。

**Comment by charley008** [comment]
清空了浏览器信息 ，cookie等一些列资料后，可以正常了
