### ISSUE TITLE
新标签页打开磁力链接，拦截功能失效。

### ISSUE THREAD

**Issue by fuxin052** [alexhua/Aria2-Explorer#127]
**Describe the bug**
如标题

**To Reproduce**
点击磁力链接的连接
任务列表没有新的任务产生

尝试过 以下操作 均无效
1. 取消 拦截磁力链接 选项 保存后 , 重新开启 拦截磁力链接 选项, 并保存
2. 取消 拦截磁力链接 选项 保存后,  卸载插件, 重新安装插件, 不使用云设置, 重新手动设置
3. 使用不同的磁力链接

并且控制台没有任何报错

PS:拦截普通任务可以正常工作

设置如下
![image](https://user-images.githubusercontent.com/46592199/229262311-66a3bec9-7858-4bda-af0f-c911b2282791.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win10
 - Browser [e.g. chrome, safari] chrome 111

**Additional context**

**Comment by fuxin052** [comment]
我安装插件使用的是chrome应用商店, 昨天(没自动升级前)可以正常拦截磁力链接

**Comment by alexhua** [comment]
多开关保存几次试试，需要弹出下面这个对话框，授权才可以生效。

![image](https://user-images.githubusercontent.com/1220458/229262831-15bacf00-116a-470d-908f-488f0245b1ea.png)

**Comment by fuxin052** [comment]
这个弹框每次都有点的

**Comment by fuxin052** [comment]
又发现了不同的地方

直接点击href是磁力链接的a链接不行
但是把链接复制到地址栏回车可以

**Comment by alexhua** [comment]
> 又发现了不同的地方
> 
> 直接点击href是磁力链接的a链接不行 但是把链接复制到地址栏回车可以

方便给了示例地址吗

**Comment by fuxin052** [comment]
可能不太对 
直接点可以
右键新窗口打开 / 点滚轮键打开 / ctrl点击打开 都不行
好麻烦

我是在动漫花园首页测试的
https://share.dmhy.org/

**Comment by fuxin052** [comment]
因为我一直都是用新窗口打开, 忽视了这个操作

**Comment by alexhua** [comment]
> 可能不太对 直接点可以 右键新窗口打开 / 点滚轮键打开 / ctrl点击打开 都不行 好麻烦

这个就可以解释通了，新页面打开是拦截不了。你先用直接单击这种方式打开，我看看后续能不能改进一下。

**Comment by fuxin052** [comment]
好的, 感谢
