### ISSUE TITLE
能否通过另一种方式来实现保存已下载记录，而非使用aria2的force-save选项？

### ISSUE THREAD

**Issue by kingofotaku** [alexhua/Aria2-Explorer#130]
**Motivation**
在扩展这一层实现保留下载记录以供日后查询，虽然force-save可以做到这一点，但每次重开aria2时下载完成但文件已被删除的项目都会被重新下载一遍（如果是我的设置有误还请告知）我只想单纯保留下载记录以备某些情况下需要查阅。

**Feature Description**
在扩展层面上将下载记录另存为一份文件
**Is the solution code ready**
No

**Willing to maintain the related code in the future**
No

**Additional context**
Add any other context or screenshots to let common user know what this feature is.

**Comment by alexhua** [comment]
这个做不了哦，Aria2的问题最好向Aria2提需求解决。
另外我这边即使删除，再次打开Aria2，任务处于等待状态并不会自动下载，你可以查查哪个配置导致了自动下载。
