### ISSUE TITLE
设置"自动下载前询问参数设置",后文件名解析有问题

### ISSUE THREAD

**Issue by BubblesYIM** [alexhua/Aria2-Explorer#133]
**Describe the bug**
设置askBeforeDownload之后如果下载的url有重定向会导致文件名不正确

**To Reproduce**
从hugging face 随意下载一个链接
原始url是这样的:
https://huggingface.co/Gavin123/lora/resolve/main/studioGhibliStyle_offset.safetensors
然后他会转到:
https://cdn-lfs.huggingface.co/repos/e6/e0/e6e0fd12c341341be7c113d268f5b3be9863aee32dde6ee4b72826cadb0067cb/6bb3719e90d33a9e88ea090cd4463d15ef68234e2acaac2a482186a8b7a30878?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27studioGhibliStyle_offset.safetensors%3B+filename%3D%22studioGhibliStyle_offset.safetensors%22%3B&Expires=1681460613&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4tbGZzLmh1Z2dpbmdmYWNlLmNvL3JlcG9zL2U2L2UwL2U2ZTBmZDEyYzM0MTM0MWJlN2MxMTNkMjY4ZjViM2JlOTg2M2FlZTMyZGRlNmVlNGI3MjgyNmNhZGIwMDY3Y2IvNmJiMzcxOWU5MGQzM2E5ZTg4ZWEwOTBjZDQ0NjNkMTVlZjY4MjM0ZTJhY2FhYzJhNDgyMTg2YThiN2EzMDg3OD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2ODE0NjA2MTN9fX1dfQ__&Signature=AekZdkwvI5euNnm%7E%7EscUI-cw3eM-OhydFM2TBKkvTcN-FSiAnG4jEVvIeceacOJVVHAvYTAF2j63vJGNpZtZjZPHzMoqHzi49FLOKl2MqI-jZ5oh5ICX4CjeT-dTk5-%7EpJEUwG2hXlFzInZvsIeAsS7XlLfYHf-ruQhCisRdDYXdftPP8N4xwfGp2d82DmtlkTGZSnImvG6cLETllJnP-z%7Ex29wvPES1u9Evw3RrEIrsJ5XKlUAzzx-qcfIK5Cd2W38Fj7cQymJWxkLk2T55OiTUjtScPTqfrZ5WChk-pZdyfn1X%7EBFxRKxLq4tMbBuNTlOVXTLICQfP8lbDW%7EqzYg__&Key-Pair-Id=KVTP0A1DKRTAX
然后手动设置文件名的话,解析到的文件名就是:
6bb3719e90d33a9e88ea090cd4463d15ef68234e2acaac2a482186a8b7a30878

**Comment by alexhua** [comment]
这个可能是Aria2的问题。自动拦截下载，文件名是由Chrome提供的，打开`askBeforeDownload` 文件名就是由Aria2自己解析了。扩展没法解决。

**Comment by BubblesYIM** [comment]
拦截到之后手动设置文件名是可以生效的,可以在打开的这个页面的时候就将文件名传进去,作为默认值

**Comment by alexhua** [comment]
> 拦截到之后手动设置文件名是可以生效的,可以在打开的这个页面的时候就将文件名传进去,作为默认值

也不是不能做，考虑到用户体验，决定采纳你的建议。
