### ISSUE TITLE
failed to download files : network problem socket operation 

### ISSUE THREAD

**Issue by silverdragon70** [alexhua/Aria2-Explorer#135]
hello,
When I try to download any file , even direct links files 
the operation failes and the download automatically transfered to stopped sections 
the error that appears is 
Task Status: Error Occurred (1)
network problem has occured 
cause a soket operation was attempted tounreachable network 
the aria2 server is connected successfully .
![Untitled](https://user-images.githubusercontent.com/9280777/232323554-4d848c7e-693c-442d-b66f-f660eefea95e.png)

**Comment by alexhua** [comment]
There is no evidence indicating that it is an extension issue according to your description.
Please check your network environment.
