### ISSUE TITLE
磁力监控出现错误

### ISSUE THREAD

**Issue by Rex0929** [alexhua/Aria2-Explorer#136]
**Describe the bug**

**To Reproduce**
在有任何磁力链接的网站点击磁力然后跳转到aria2ng后显示的磁力都是错误的
![image](https://user-images.githubusercontent.com/62170324/233541423-386eceb9-2eb1-44ff-b9ab-b16cbfa65382.png)
出现的却是
![image](https://user-images.githubusercontent.com/62170324/233541476-00d5df16-e7c0-44e1-8e23-e91db8b7bbc5.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows11
 - Browser Chrome
 - Version 2.0.2
![image](https://user-images.githubusercontent.com/62170324/233541562-893e165f-e923-4195-a2e3-c70198afbcb3.png)

**Additional context**

**Comment by alexhua** [comment]
感谢反馈，这个问题已经注意到了。

**Comment by alexhua** [comment]
fac58ebbdc5bb37ed00bce3668100ed2176dd56d
