### ISSUE TITLE
无法正常拦截Github的文件下载，比如release下载

### ISSUE THREAD

**Issue by cesaryuan** [alexhua/Aria2-Explorer#138]
**Describe the bug**
点击release中的文件下载时，拦截到的下载链接有问题导致不能下载。

**To Reproduce**
1. Go to [alexhua/Aria2-Explorer: An aria2 download task management extension for chromium based browser](https://github.com/alexhua/Aria2-Explorer/releases/tag/v2.0.2)
2. Click on [Aria2Explore-V2.0.2.crx](https://github.com/alexhua/Aria2-Explorer/releases/download/v2.0.2/Aria2Explore-V2.0.2.crx) to download.
3. Click the `Download` button.
4. See the error

**Expected behavior**
No error.

**Screenshots**

https://user-images.githubusercontent.com/35998162/233928789-4e992121-9996-4386-aad8-bafe84e19b29.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 102.0.5005.167

**Additional context**

**Comment by PrinceOC912** [comment]
I am on brave and facing the same problem, haven't been able to download anything from GitHub for a few days.

**Comment by alexhua** [comment]
感谢反馈，可以复现， 可能是URL传给AriaNG编解码的时候出了问题。

**Comment by alexhua** [comment]
## To NewComer:
### This is a very good example of submitting a question, hoping everyone can refer to it.
