### ISSUE TITLE
浏览器图标显示状态异常

### ISSUE THREAD

**Issue by dlk48920101** [alexhua/Aria2-Explorer#139]
设置里勾选任务通知状态，链接方式为HTTPS+域名链接。浏览器插件图标会不停的链接失败和成功之间切换，具体表现为插件图标右下角一会变红色一会变绿色。任务通知状态取消勾选就没有这个情况了。

**Comment by alexhua** [comment]
我猜是你的域名Websocket连接的问题。 在ariaNG设置中，把RPC协议改成websocket安全协议试试，如果连不上说明不是扩展的问题。
![image](https://user-images.githubusercontent.com/1220458/234666709-f0d0794c-02f2-41ad-a3f9-6d0c791a3e01.png)

**Comment by alexhua** [comment]
另外下次提交issue，最好按模板填写完整信息，方便定位问题。

**Comment by alexhua** [comment]
close for no further response.
