### ISSUE TITLE
[Suggestion] When no task is going, better hide the coner "0" hint. 建议不要显示0"角标

### ISSUE THREAD

**Issue by sherlocknieh** [alexhua/Aria2-Explorer#142]
![image](https://github.com/alexhua/Aria2-Explorer/assets/43476643/6d288544-ae93-4a61-93da-4711c7484fdc)

首先，不要叫我关闭角标通知监测。有下载任务时我需要这个通知。
但是没有下载任务时，它的存在吸引了不必要的注意力。

**Comment by sherlocknieh** [comment]
本来我只是好心反馈一下，给你提供了一些信息：“有人可能会被这个设计干扰到”。你可以看看，作为参考。
但你这回复的态度就是：”你的意见不重要，我拒绝参考，我的地盘我做主“。你这还不如不回复呢。
所以你引发了我一系列无法抑制住的回复，如果你被打扰了，那也是你傲慢的态度造成的。

以上也是一些关于人的反应的参考，听不听在你，再见！

@alexhua

**Comment by sherlocknieh** [comment]
你再想想你这两条要求有没有问题：

> 什么样的问题会被重视？
> 有建设性的特性或功能建议
> 扩展本身存在的问题且有详细的复现步骤

我给你翻译翻译：
给你免费提供创意和找Bug，可以。
给你提要求，不行。

@alexhua

**Comment by alexhua** [comment]
好家伙，你让我开眼了，再见~
