### ISSUE TITLE
[Suggestion] When no task is going, better hide the coner "0" hint. 建议不要显示"0"角标

### ISSUE THREAD

**Issue by sherlocknieh** [alexhua/Aria2-Explorer#143]
![image](https://github.com/alexhua/Aria2-Explorer/assets/43476643/6d288544-ae93-4a61-93da-4711c7484fdc)

首先，不要叫我关闭角标通知。有下载任务时我需要这个通知。
但是没有下载任务时，它的存在吸引了过多不必要的注意力。

**Comment by alexhua** [comment]
这种需求就属于个人习惯了，比较琐碎的需求，改了可能有另一部分人不乐意了。

**Comment by sherlocknieh** [comment]
> 这种需求就属于个人习惯了，比较琐碎的需求，改了可能有另一部分人不乐意了。

我的理由已经说得很充分了，这个东西的存在客观上就是会吸引注意力，我不相信什么人会不乐意减少干扰！

**Comment by sherlocknieh** [comment]
> 这种需求就属于个人习惯了，比较琐碎的需求，改了可能有另一部分人不乐意了。

另外，我如果不是被干扰次数过多，超过了忍受的阈值的话，根本就不会因为什么 “个人喜好” 的原因找到这里来浪费时间给你写一堆东西！
@alexhua

**Comment by alexhua** [comment]
先平复下你的情绪，这么做肯定有这么做的道理，我就不解释了。我提供免费软件，还要给用户再解释一遍为什么，是不是也很累。所以，年轻人要多多去理解这么世界，为什么不是你希望的样子。提高自己的适应能力，路才能走得更顺。

**Comment by alexhua** [comment]
好家伙，你让我开眼了，再见~
