### ISSUE TITLE
[Feature Request] Auto start Motrix if it not started

### ISSUE THREAD

**Issue by yswtrue** [alexhua/Aria2-Explorer#144]
**Motivation**
Auto start Motrix if it has not started

**Feature Description**
* capture the download URL
* Check if Motrix started
* auto start motrix if Motrix not started

**Is the solution code ready**
No

**Willing to maintain the related code in the future**
Yes

**Additional context**

**Comment by yswtrue** [comment]
can [Native Message](https://developer.chrome.com/docs/extensions/mv3/nativeMessaging/) resolve this problem?

**Comment by alexhua** [comment]
> can [Native Message](https://developer.chrome.com/docs/extensions/mv3/nativeMessaging/) resolve this problem?

Maybe not.
I think this feature is out of extension's scope.  At first, we need a message host or Motrix runing as a message host.

**Comment by alexhua** [comment]
After V2.1 was released, you could register Motrix as the default application of `aria2://` protocol. And then start Motix by clicking on  `Start Aria2` from extension option menu.

Reference: [How to Register an Application to a URI Scheme](https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767914(v=vs.85)?redirectedfrom=MSDN)
