### ISSUE TITLE
希望增加快捷键动态拦截下载

### ISSUE THREAD

**Issue by idevmo** [alexhua/Aria2-Explorer#145]
首先感谢大佬开发，今天才发现这款软件，相识恨晚。
刚开始用这款插件，结合自己的使用场景有些小建议，正常下载在本地，只有某些资源想通过aria2远程下载到Nas里面。
不确定是否已经有这些功能，如果没有的话希望大佬可以考虑下。

比如默认不拦截下载，当按住Ctrl键点击时才拦截；
又或者像IDM一样，按住Alt键点击时不拦截下载。

还有就是目前拦截下载好像没啥提示，需要打开AriaNG再确认一遍是否已经成功添加。

再次感谢大佬，希望能够采纳

**Comment by alexhua** [comment]
#59
