### ISSUE TITLE
V2.1.0 拦截功能无法正常下载 (Extension could not  send download task to Aria2 )

### ISSUE THREAD

**Issue by wdkGitHub** [alexhua/Aria2-Explorer#147]
Motrix + Aria2 插件 2.1.0 总是下载错误, 打开 自动下载前询问参数设置 再手动点击下载可以下载

是不是有bug 了 ,之前版本2.0.5 可以正常使用

**Comment by alexhua** [comment]
感谢反馈，拦截下载出了一些小问题。

临时解决办法：
打开`AriaNG`，随便改一些`Aria2设置`就可以了。

**Comment by wdkGitHub** [comment]
错误代码 ：https://github.com/agalwood/Motrix/wiki/Error#16



<img width="737" alt="image" src="https://github.com/alexhua/Aria2-Explorer/assets/12813051/92764133-f46c-4e9f-98ff-8b1c2e0739d3">

**Comment by wdkGitHub** [comment]
修改 Aria2设置里面的下载路径，能解决。路径哪怕不变，只要触发保存修改就行。
<img width="1238" alt="image" src="https://github.com/alexhua/Aria2-Explorer/assets/12813051/ae09714a-9f27-41de-b48b-54fc75d54694">

**Comment by alexhua** [comment]
> 修改 Aria2设置里面的下载路径，能解决。路径哪怕不变，只要触发保存修改就行。

是的，应该是这样子，感谢反馈。

修复版v2.1.1 a8843f265f5188bfac5d8ed5d0ffd811ae6611c7 已经提交，应该很快能上架。

也可以下载安装[GitHub版本](https://github.com/alexhua/Aria2-Explorer/releases/download/v2.1.1/aria2e-v2.1.1.crx)，和商店版时一样的。下载，并打开`chrome://extensions/`，然后拖入即可。

**Comment by alexhua** [comment]
v2.1.1 已上架。
