### ISSUE TITLE
不填写download location时拦截下载的文件会被下载到aria2主程序所在的目录

### ISSUE THREAD

**Issue by fuxin052** [alexhua/Aria2-Explorer#149]
**Describe the bug**
如标题

**Expected behavior**
不填写download location时应该下载到aria2全局设置的目录中
所以此时调用接口应该不传dir参数

**Screenshots**

![image](https://github.com/alexhua/Aria2-Explorer/assets/46592199/6e013aa6-b678-4456-a95a-ebaf96435696)

![image](https://github.com/alexhua/Aria2-Explorer/assets/46592199/af45c066-11c0-4c21-b976-6dce38177391)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 2.1.1

**Comment by alexhua** [comment]
逻辑确实不完善，感谢反馈。
