### ISSUE TITLE
能否把菜单 [正在下载、正在等待、已完成/已停止] 合并成一个列表

### ISSUE THREAD

**Issue by wdkGitHub** [alexhua/Aria2-Explorer#151]
<img width="602" alt="image" src="https://github.com/alexhua/Aria2-Explorer/assets/12813051/45f8b93c-3c51-4fb1-955c-9f7ececbf849">

能否把菜单 [正在下载、正在等待、已完成/已停止] 合并成一个列表，每次下载完都要点击到 已完成菜单，在已完成菜单又看不到正在下载的进度。

**Comment by alexhua** [comment]
讲道理这个布局我也是很想改。不过，关于下载任务Aria2它就是这么分类的，而且ariaNG也是照这个思路来的。如果我这边改，以后的维护升级可能很Boring，所以这个问题最好提给ariaNG作者。

**Comment by wdkGitHub** [comment]
原来如此
