### ISSUE TITLE
能否实现下载过程中对文件类型和大小进行筛选？

### ISSUE THREAD

**Issue by marslulu** [alexhua/Aria2-Explorer#152]
有时候一个torrent文件中涉及太多垃圾文件，比如我只想下载其中后缀名为.mp4或.avi，文件大小不小于120M的文件，不知如何设置？谢谢啦

**Comment by alexhua** [comment]
[#107#issuecomment-1665283118](https://github.com/alexhua/Aria2-Explorer/issues/107#issuecomment-1665146336)
