### ISSUE TITLE
Can not delete Aria2-RPC-Server

### ISSUE THREAD

**Issue by Sinute** [alexhua/Aria2-Explorer#153]
**Describe the bug**
After add an Aria2-RPC-Server， can not find any way to delete it

**To Reproduce**
1. click "Add RPC"
2. fill in and save
3. now you can't delete it

**Expected behavior**
may be there should be a delete button

**Screenshots**
![1](https://github.com/alexhua/Aria2-Explorer/assets/2202852/46b522ff-04af-43e9-8b37-3bbd84e8b92c)

**Desktop (please complete the following information):**
 - OS: windows11
 - Browser chrome
 - Version 114.0.5735.248

**Comment by alexhua** [comment]
Thank you for your feedback.
A commit (680fa684807e39f989f6c1c40c2f5143b94a6f2f) has been made and is awaiting release.
Following this, you will be able to delete an RPC item by clearing its content and saving the configuration.
