### ISSUE TITLE
aria2 explorer拦截磁力链接打开再关闭后别的软件无法正常拦截磁链进行下载

### ISSUE THREAD

**Issue by carrotluo5** [alexhua/Aria2-Explorer#155]
前提：我在使用aria2 explorer之前点击网页中的磁力链接会自动跳转到关联程序（迅雷、Motrix）。
使用aria2 explorer之后，按照说明手动关闭了磁力链接拦截，但此时再点击磁力链接却无任何反应。
尝试过重启浏览器，重启电脑，重新安装插件打开再关闭，均无效。希望能得到一个解决方法。

**Comment by alexhua** [comment]
#98
