### ISSUE TITLE
Vivaldi 浏览器无法拦截默认下载

### ISSUE THREAD

**Issue by Mivimcrs** [alexhua/Aria2-Explorer#158]
在 Vivaldi 浏览器无法拦截下载，还是会启动浏览器自带下载，已经尝试了多个网站。

## 版本
浏览器：Vivaldi 6.2.3105.48
系统：Win11 22H2 22621.2283
插件：v2.1.4
Aira2：Motrix

**Comment by alexhua** [comment]
#64
