### ISSUE TITLE
疯狂报错“无法连接到Aria2”，但是实际上下载正常进行，弹窗导致无法操作

### ISSUE THREAD

**Issue by AgMonk** [alexhua/Aria2-Explorer#162]
![image](https://github.com/alexhua/Aria2-Explorer/assets/31527430/cb362c00-1b8f-4a78-942b-2be65b6839bb)

下载列表的进度正常更新，F12 的网络标签请求结果一切正常

控制台打印报错

通过清空控制台和网络请求来观察，是 aria2.getGlobalStat 或  aria2.getGlobalOption 请求之一导致的报错，这两个请求以相同间隔发出，无法区分是哪个。

复现方法未知，只有一台设备出现这个问题。

Chrome版本： 版本 117.0.5938.150（正式版本） （64 位）

扩展版本： 2.1.4

**Comment by alexhua** [comment]
看不出来是哪的问题，最好能提供复现步骤。

**Comment by alexhua** [comment]
赶巧复现了一次， 大致猜到什么原因了。可能是你在没连Aria2的时候改了某个Aria2设置，触发了这个Bug。感谢反馈。

**Comment by alexhua** [comment]
**临时解决方案：**

- 先关闭Aria2程序，然后去`常规设置`最下面点`重置Aria2设置`，应该会恢复正常。
- 默认值为空且没有在conf文件里配置过的Aria2设置项先不要修改，可以暂时避免这个问题。

**Comment by alexhua** [comment]
b8a234c2065832e7d093cb6a8a1ec347f6251d73
