### ISSUE TITLE
右键导出下载链接，「导出前询问详细参数设置」选项失效

### ISSUE THREAD

**Issue by nukewarrior** [alexhua/Aria2-Explorer#164]
<img width="974" alt="image" src="https://github.com/alexhua/Aria2-Explorer/assets/10683831/1be974db-45b6-4ff3-89d1-3e25385b1ffe">

如图设置，在旧版本中（抱歉，无法确认具体是哪个版本），右键导出不会弹出详细设置页面。
新版v2.2.2中如图设置，使用右键导出依旧会弹出详细设置页面，只有将红框2个选项全部设定为关闭，才会不弹出详细设置页面。

**Comment by alexhua** [comment]
感谢反馈。
1f94a15aab20dafb455a07ef6a48b46e17c15c82
