### ISSUE TITLE
取消勾选 自动下载前询问参数设置 会丢失 cookie

### ISSUE THREAD

**Issue by xxldm** [alexhua/Aria2-Explorer#165]
![3](https://github.com/alexhua/Aria2-Explorer/assets/38677850/0bc5a412-0ffd-4d83-9063-862c27c2b1ec)

取消勾选 自动下载前询问参数设置，下载时查看请求头没有携带cookie
![1](https://github.com/alexhua/Aria2-Explorer/assets/38677850/389e4417-bf86-4f58-a259-c9af83071442)

勾选 自动下载前询问参数设置，下载前和下载时都可以正常携带cookie
![2](https://github.com/alexhua/Aria2-Explorer/assets/38677850/9c35e9b8-0fb3-42d6-8e6a-175c5172f7a4)

下载内容 | google drive分享的文件
-- | --
aria2来源 | Docker Desktop wsl2部署
扩展版本 | v2.2.1

**Comment by alexhua** [comment]
感谢反馈这个在v2.2.2已经修复了。
1450c8e

**Comment by xxldm** [comment]
感谢大佬，大佬辛苦了，edge浏览器插件商店还没更新，我从chrome商店下了，可以正常携带cookie。Docker Desktop部署的容器，可以使用localhost直连。
