### ISSUE TITLE
无法显示上传速度？

### ISSUE THREAD

**Issue by why175003** [alexhua/Aria2-Explorer#167]
无论下载期间，还是做种期间都无法显示上传速度？
<img width="476" alt="Snipaste_2023-11-16_23-57-23" src="https://github.com/alexhua/Aria2-Explorer/assets/143988577/5052c1f4-0343-428a-9962-980c7a6ee682">

**Comment by alexhua** [comment]
#59
![image](https://github.com/alexhua/Aria2-Explorer/assets/1220458/891d64a8-bd45-45b9-b4bc-61ecd8e77c41)
