### ISSUE TITLE
[Feature Request] Category or Catalog menu for Donwload Path

### ISSUE THREAD

**Issue by BoscoFZ** [alexhua/Aria2-Explorer#168]
This is my suggestion for adding a category to Download Path.
 
For example, in the Download Capture section in Extension Option Settings, I have selected the "Ask detail settings before auto download" option. So every time I download a file, it will display the Options page and I can add the Donwnload Path that I want to download. I know in the Donwnload Path section you have a function to remember the previously downloaded path so that when you need to download, you just need to select the desired path again. But if my path is too long or too many paths are displayed, it will be easy to choose the wrong path.
If possible, you could create a type function to create Category or Catalog types and assign the corresponding path to each type, I think it would be even easier to use.

For example, I create 2 items, Music and Movie, in Category or Catalog and assign the paths to them as C:\Users\User\Downloads\Music and C:\Users\User\Downloads\Movie.
When I'm downloading a music file, I just need to select Music in Category or Catalog and it will automatically assign the Donwnload Path to C:\Users\User\Downloads\Music that I configured before.

Thank you for reading my article, I really appreciate and hope you can do this if possible.

**Comment by alexhua** [comment]
A solution for you:

- Create more Aria2-RPC-Server items with the same RPC URL but variety download locations  for extension and take the category as RPC name.
- Then you are able to select the download category by right-clicking the download link (Ensure that `Ask details before export` is disabled ). 
- Even, the extension could automatically select the category after you configure the URL patterns for each RPC item properly, if the `Ask details before auto download` is off.

For more detail, you could refer to #76.

**Comment by BoscoFZ** [comment]
Thank you for the solution you suggested, I followed your instructions and found it worked exactly as I wanted. Thanks for your support.
