### ISSUE TITLE
I can't block all chrome downloads unless I manually right click Add to aria2-Explorer

### ISSUE THREAD

**Issue by shinianyunyan** [alexhua/Aria2-Explorer#169]
**Describe the bug**
No matter what I download can not be blocked, but directly use chrome's own download, unless I manually right-click to add to aria2-Explorer can be called normally.

**To Reproduce**
1. Select any of the download buttons and click Download 
2. chrome calls its own download to download

**Expected behavior**
The download task is taken over directly by aria-Explorer and successfully downloaded.

**Screenshots**
![image](https://github.com/alexhua/Aria2-Explorer/assets/93144521/3f2f7e98-9766-4b32-937b-787496286ce6)

**Desktop (please complete the following information):**
 - OS: windows11 23H2
 - Browser: chrome
 - Version: 119.0.6045.160 (Official Version) (64-bit)

**Comment by alexhua** [comment]
Can not reproduce. 
Could you please supplement more details to reproduce it definitely?

**Comment by alexhua** [comment]
No response for a week.

**Comment by shinianyunyan** [comment]
emmm，你可以把这个issue删掉么，反正这个也没有什么可参考等价值，并且也已经关闭了，但应该是因为我在这里提了问题，所以我的首页的Top repositories中老是会显示你们这个项目，虽然很好用，但一直显示着看着很难受（有较强烈的强迫症），如果可以请删除此issue，感激不尽！
![55263f5b-d515-48d5-aa75-77ecfb77d06f](https://github.com/user-attachments/assets/7c0592ba-2d90-4251-a126-111354024ab7)
