### ISSUE TITLE
可不可以出一个不带AriaNG前端的lite版本？

### ISSUE THREAD

**Issue by Tback1** [alexhua/Aria2-Explorer#171]
AriaNG我用起来始终不觉得比YAAW顺手，尤其是正在下载与下载后已下载文件的的分组、排序始终是个老大难问题。
考虑到A2E自己添加了一个全部下载的tab页，能否考虑这个页上增加一个分组将正在下载和已下载分组一下
类似
![image](https://github.com/alexhua/Aria2-Explorer/assets/8872546/cea5d0a9-405a-4305-aa56-cbb2d410aacc)
AiraNG的issue也有人提类似这个的需求 https://github.com/mayswind/AriaNg/issues/735

如果上述方案实现难度过大
考虑到换了Chrome Store里其他几个[Integration]，拦截和重命名的能力都不如Aria2-Explorer，但AriaNG默认真是挺难受的。估计请求作者打包一个带YAAW的版本那更是痴心妄想，是否考虑发布一个不带前端的版本？

**Comment by alexhua** [comment]
最近的版本已经对AriaNG做了改进，全部任务里的`默认`分组方式就是按`正在下载->暂停->错误->已完成`的状态分组的，只是没有像YAAW这样直白的显示出来。没明白不带前端的版本是什么意思，有啥好处。当然维护多个版本也是不太现实的，不如集中精力改进一个版本。不妨详细说说你的痛点在哪里，或者有时候是适应问题，适应一段时间就好了。

**Comment by alexhua** [comment]
本来写了一大段，想想还是直接说结论吧，可能还是YAAW更适合你。

关于第一点，下一版会有一点小改进，让不同的状态区分得更明显，但不会做成YAAW那样。

关于第二点，曾经也是想改的。你可以提给AriaNG试试，上游如果改了我会跟进。

开源就是这样，各有各的问题。用户体验这事也是见仁见智，我能做的就是在各种方案之间做平衡，尽量在不增加工作量的情况下整合各个模块。

最后，感谢反馈。

**Comment by Tback1** [comment]
完全可以理解~不强求，只提出issus请开发者考量，能实现固然好，不能也仅供参考~

**Comment by alexhua** [comment]
> 完全可以理解~ 不强求，只提出issus请开发者考量，能实现固然好，不能也仅供参考~

下一版会出一个**紧凑模式**

![TaskList-1](https://github.com/alexhua/Aria2-Explorer/assets/1220458/8b650974-a7ba-446e-b8d5-c8bad9a94453)
![TaskList-2](https://github.com/alexhua/Aria2-Explorer/assets/1220458/f14ede48-e03b-4fa3-b726-f83e0a5f9c2f)
