### ISSUE TITLE
Unable to return the correct RPC Download Path (dir) value after importing settings for AriaNg Settings

### ISSUE THREAD

**Issue by BoscoFZ** [alexhua/Aria2-Explorer#174]
I created 2 new PRCs, A and B, and I assigned the download path values to them as "C:\Users\User\Downloads\Music\" and "G:\Game\".

And here is my export settings data

{
  "language": "en",
  "theme": "light",
  "title": "${downspeed}, ${upspeed} - ${title}",
  "titleRefreshInterval": 5000,
  "browserNotification": false,
  "browserNotificationSound": true,
  "browserNotificationFrequency": "unlimited",
  "rpcAlias": "Aria2",
  "rpcHost": "localhost",
  "rpcPort": "6800",
  "rpcInterface": "jsonrpc",
  "protocol": "http",
  "httpMethod": "POST",
  "rpcRequestHeaders": "",
  "rpcOptions": {
    "dir": "Downloads"
  },
  "secret": "",
  "extendRpcServers": [
    {
      "rpcAlias": "A",
      "rpcHost": "localhost",
      "rpcPort": "6800",
      "rpcInterface": "jsonrpc",
      "protocol": "http",
      "httpMethod": "POST",
      "rpcRequestHeaders": "",
      "secret": "",
      "rpcOptions": {
        "dir": "C:\\Users\\User\\Downloads\\Music\\"
      },
      "rpcId": "QXJpYU5nXzE3MDEwNzUwMDdfMC4yMzA0NzQ5MzAzNDQyNzA1OA=="
    },
    {
      "rpcAlias": "B",
      "rpcHost": "localhost",
      "rpcPort": "6800",
      "rpcInterface": "jsonrpc",
      "protocol": "http",
      "httpMethod": "POST",
      "rpcRequestHeaders": "",
      "secret": "",
      "rpcOptions": {
        "dir": "G:\\Game\\"
      },
      "rpcId": "QXJpYU5nXzE3MDEwNzUwMDJfMC45ODMyMzQ5MzM5MDM3MTc2"
    }
  ],
  "webSocketReconnectInterval": 5000,
  "globalStatRefreshInterval": 1000,
  "downloadTaskRefreshInterval": 1000,
  "keyboardShortcuts": true,
  "swipeGesture": true,
  "dragAndDropTasks": true,
  "rpcListDisplayOrder": "recentlyUsed",
  "afterCreatingNewTask": "task-list",
  "removeOldTaskAfterRetrying": false,
  "confirmTaskRemoval": true,
  "includePrefixWhenCopyingFromTaskDetails": true,
  "showPiecesInfoInTaskDetailPage": "le10240",
  "afterRetryingTask": "task-list-default",
  "displayOrder": "default:asc",
  "fileListDisplayOrder": "default:asc",
  "peerListDisplayOrder": "default:asc",
  "defaultTaskPage": "all",
  "recCount": 4
}

Then I tried to Import settings using the export settings data I just had above, but as a result, I saw that the Download Path (dir) of A and B both changed to Downloads like that of Aria2.

Can you help me correct it so that when importing settings, it returns the correct RPC Download Path (dir) value? Thank you very much.

**Comment by alexhua** [comment]
Thanks for feedback.
There is a bug that all the Aria2 options will be ignored when importing settings.
We will fix it in the next version.
