### ISSUE TITLE
希望下载某网盘直链时能获得正确的下载名称

### ISSUE THREAD

**Issue by nil-ref** [alexhua/Aria2-Explorer#175]
https://zhuanlan.zhihu.com/p/463701329

链接例子:
```https://yq01-cu01.baidupcs.com/file/09df287bfn7fd074fb5ca37154fb5668?bkt=en-3f603aaf96443402753f7c2fbc13b0cb6f041accb0415365db2659aec24550f4f7c27a91dd4ecb6cdd527d9f2595e77fc2c73115ae91a63700cb1867fe7d9da2&fid=4186282961-250528-152344629363633&time=1701233392&sign=FDTAXUbGERQlBHSKfWaqiu-DCb740ccc5511e5e8fedcff06b081203-wVYuB%2Bh270E9xkPvcjb9JPxdr58%3D&to=229&size=197371516&sta_dx=197371516&sta_cs=42&sta_ft=rar&sta_ct=7&sta_mt=0&fm2=MH%2CYangquan%2CAnywhere%2C%2C%E5%8C%97%E4%BA%AC%2Ccnc&ctime=1635146003&mtime=1701170675&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=197371516&vuk=1511013237&iv=2&htype=&randtype=&tkbind_id=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-249f2bcf89b63a136589b24b1ce33e58bfa85392343d6c1db799c3415118eed9353272d477778ae157ba4b71b5e5d04a977fe8f5c02b7c3b305a5e1275657320&expires=8h&rt=sh&r=152122877&vbdid=2548920604&fin=QSanguosha.0610.Chs.Green.Edition-ALI213.rar&rtype=1&dp-logid=8865338366571132897&dp-callid=0.1&tsl=0&csl=0&fsl=-1&csign=cAR8wpepCLlTQOyrX8HwPqpicb4%3D&so=1&ut=1&uter=0&serv=0&uc=3031334550&ti=068bcab50ae430c735fd030657a9508ef45b4b9fa97e249a&hflag=30&from_type=3&adg=c_c958a16d4c83fdf4877384e443817d17&reqlabel=250528_f_7dfd979dfe4f708e26ae090bfb30fdcf_-1_0657c007d7abfaef30c37ade49379dc9&by=themis&resvsflag=1-12-0-1-1-1```

我是通过手动新建链接下载的. 最后得到的是hash文件名.

**Comment by alexhua** [comment]
在 AriaNG 的`Aria2设置`->`高级设置` 把`content-disposition-default-utf8` 打开
