### ISSUE TITLE
无法正确转发 1fichier.com 的下载

### ISSUE THREAD

**Issue by poly000** [alexhua/Aria2-Explorer#176]
**Describe the bug**
referr，UA都确定一致，代理设置一致，仍报错410错误，浏览器内暂停后可以继续下载

**To Reproduce**
从 1fichier.com 下载任意文件
弹窗提示转发后确认下载任务

**Expected behavior**
可以正确进行下载

**Screenshots**

**Desktop (please complete the following information):**
windows
chrome 119
aria2 1.37.0

**Additional context**

**Comment by alexhua** [comment]
试了下，网站有保护，拦截的是一次性链接。拦截后下不了很正常的。

到这一步的时候，复制链接，然后手动创建下载，不用填UA，也不用填Referrer，**Aria2**可以正常下。
![image](https://github.com/alexhua/Aria2-Explorer/assets/1220458/3e3ceac2-6b73-468f-b996-889b337c4817)
