### ISSUE TITLE
是不是和其他代理扩展会冲突？

### ISSUE THREAD

**Issue by KangMz** [alexhua/Aria2-Explorer#177]
1. 我有使用一款代理扩展 Porxy SwitchyOmega，但是可能由于我用的是一些没有安全保障的无名小机场。然后我偶然发现我下载文件时，任务虽然创建了速度一直是0KB，直到我把Porxy SwitchyOmega的代理关闭，使用直接连接后，一切就正常了，任务立刻就有了速度，并且下载完成。我想知道这种情况是符合预期的吗，如果是的话，如何避免这种情况发生？

2. 似乎和 Motrix1.8.19 不太兼容，以前添加任务的时候在Motrix会同步显示，但是目前只会在[Aria2-Explorer]中才能查看到任务，而Motrix中不显示了。由于我把Motrix更新了，并且[Aria2-Explorer]也自动更新到了2.X的版本，我不太确定发生这种情况的原因是什么

**Comment by alexhua** [comment]
#59
