### ISSUE TITLE
The most convenient download manager for aria2.

### ISSUE THREAD

**Issue by paolosezart** [alexhua/Aria2-Explorer#179]
I have tried several download managers for aria2. Your browser extension has proven to be the most convenient and stable. I have added Aria2-Explorer to all devices that have chrome. However, on the raspberry pi I use firefox. I would really like it if you could make your own browser extension for firefox. As it is the most convenient (especially the ability to switch between multiple devices). I have tried many analogs, but other extensions either do not have the necessary functionality or are not stable. 
Thanks in advance!

**Comment by alexhua** [comment]
Thanks for you appreciation, but no plan right now as I explained in #77.
