### ISSUE TITLE
新版本的让浏览器自带的下载有很大延迟

### ISSUE THREAD

**Issue by wutongskype** [alexhua/Aria2-Explorer#182]
开启这个插件 不开拦截 用浏览器自带的下载 下载任何文件都会有30秒左右的延迟...

**Comment by alexhua** [comment]
> 开启这个插件 不开拦截 用浏览器自带的下载 下载任何文件都会有30秒左右的延迟...

无法复现，请按照issue模板提供详细的复现步骤和版本信息。
