### ISSUE TITLE
Default Aria2NG styles

### ISSUE THREAD

**Issue by medicamin** [alexhua/Aria2-Explorer#184]
**Feature Description**
This project adds lots of enhancements and features to the default Aria2NG backend. So it has more functionality.
Well done...

Is there any chance that you release a version of Aria2-Explorer which uses the original Aria2NG styles and animations? I Have an old PC which is not able to handle animations well. (i.e blur effect in right click menu, hovering items, download progress and more...). They are too laggy. But the original Aria2NG works without lags (at the same version).

**Comment by alexhua** [comment]
I am sorry not.
You may access the original AriaNG at http://ariang.mayswind.net/latest/
