### ISSUE TITLE
turbobit.net does not work.

### ISSUE THREAD

**Issue by vcheckzen** [alexhua/Aria2-Explorer#186]
**Motivation**

turbobit.net is a file sharing site which has very slow download speed and only allows one connection to download files. Using pc to download files from it costs much time and energy, so I want it to be downloaded by aria2 in another low energy cost machine.

After many attemps, in each time, even though tasks can be send to aria2 with correct cookies, the site always returns 403. I hope the developers of this project help me analyse if there is a possibility to make aria2 successfully download files of this site.

**Feature Description**

Want this site to be supported.

**Is the solution code ready**

No

**Willing to maintain the related code in the future**

Yes

**Additional context**

Here is a test link <https://turbobit.net/6yqzyp4347s6.html>, and the following images are downloading steps.

![1](https://github.com/alexhua/Aria2-Explorer/assets/18008498/486cad69-3c25-4d67-aa00-3943ed4512d2)

![2](https://github.com/alexhua/Aria2-Explorer/assets/18008498/56d274ae-34f7-455c-a12e-6494a4d7324d)

![3](https://github.com/alexhua/Aria2-Explorer/assets/18008498/7294135c-b7ad-490a-bb17-eea7004749bc)

**Comment by alexhua** [comment]
#59
