### ISSUE TITLE
有关任务数量角标的一些优化建议

### ISSUE THREAD

**Issue by Giresharu** [alexhua/Aria2-Explorer#187]
目前只要打开了检测 aria2 状态，即使没有任何正在执行的任务，也会始终显示一个 0 的角标，不仔细查看无法立刻分辨出是否有任务正在执行。所以我想提一个关于角标的优化建议供参考：

- 出现失败任务，则显示为 X ，优先度最高，覆盖其余任何角标，直到用户点击一次扩展后恢复其他角标（也可以只要有失败任务就一直显示，不过因为AriaNG需要几步操作来删除失败任务，有点麻烦，我建议只要确认过后就不显示）；
- 当有正在进行的下载任务的时候，显示绿色角标；
- 当仅有暂停任务时，显示黄色的 | | 表示暂停；
- 没有任何任务时，不显示角标；

流程图是这样的：
![2024226-194846](https://github.com/alexhua/Aria2-Explorer/assets/20269055/3d6e8a61-c58e-41ef-bc79-7f2702251ec6)

**Comment by alexhua** [comment]
Less is more, 暂时不打算改了，你的建议留着以后做参考。
