### ISSUE TITLE
[BUG] 求助，无法保存扩展的选项参数

### ISSUE THREAD

**Issue by easythd** [alexhua/Aria2-Explorer#188]
CHROME 122版本。
第一次从chrome商店安装时，选项页是正常的，其中有默认的一些配置是打开的，配置了参数可以保存，比如右键导出下载默认就是选上的，试了下右键里也有导出到ariang。
当时我不太懂配置页最下方的“配置云端同步”，就点了一次下载，又点了一次上传，都没啥反应我就没管了。当我关了选项页去看别的，等一会儿我再次打开选项页时，就发现页面中所有参数都是无选择的状态，包括自动拦截文件大小那个文本模式都是空的，啥也没有。这时选择任何参数，点保存，都是会刷新下页面，又是空的，试了下这些配置也都没生效，比如右键导出下载，现在右键里没有这个菜单项了。
于是我删除扩展，再次从chrome商店安装，装好了扩展后会自动打开选项页，直接就是全部没选择的样子，所有框也是空的。
我删除重装3次都不行。也在chrome的User Data\Default\Extensions\mpkodccbngfoacfalldjimigbofkhgjn这个文件夹看了，删除扩展后，这个文件夹是没有了的。
不明白为啥了。

选项页现在截图如下：
![捕获](https://github.com/alexhua/Aria2-Explorer/assets/70197314/6b0d3a4a-83fa-44bf-b9d3-0234a7b72d69)

发现在浏览器控制台有报错，截图如下：看不懂
![捕获1](https://github.com/alexhua/Aria2-Explorer/assets/70197314/9c1ecdd6-cf07-44ff-84dc-b8c77b553bb0)

**Comment by alexhua** [comment]
代码确实有点问题，不过貌似是触发了Chrome的bug。重启系统后还有这个问题吗？

**Comment by easythd** [comment]
重启系统还是一样，又重装了扩展也是

Alex Hua ***@***.***> 于 2024年3月15日周五 19:20写道：

**Comment by alexhua** [comment]
> 重启系统还是一样，又重装了扩展也是 Alex Hua ***@***.***> 于 2024年3月15日周五 19:20写道：

v2.4.0版下载一个空的配置，会导致 AriaNG 无响应，但没法复现你这种情况。

`IO error: .../LOCK: Access denied (ChromeMethodBFE: 15::LockFile::2)` 是 Chrome 读取扩展的配置文件被拒绝，更像是文件权限问题，这个不是扩展本身的问题。你可以回想一下当时做了哪些操作，导致了 Chrome 读取文件被拒。

另外，你可以试试卸载扩展后，在 Chrome的 **User Data\Default** 搜索一下 **mpkodccbngfoacfalldjimigbofkhgjn** 看看有没有文件残留。

**Comment by easythd** [comment]
卸载扩展后，我看过没有扩展文件夹残留的，我反复装过几次都观察过了。
卸载后文件夹被删除，安装了又出现，看起来正常。

Alex Hua ***@***.***> 于 2024年3月16日周六 11:29写道：

**Comment by alexhua** [comment]
> 卸载扩展后，我看过没有扩展文件夹残留的，我反复装过几次都观察过了。 卸载后文件夹被删除，安装了又出现，看起来正常。

看你的截图是Linux？我取消了 **google-chrome/Defautl/Loal Extension Settings/mpkodccbngfoacfalldjimigbofkhgjn** 的访问权限，能完美复现的你问题，所以你可以顺着权限管理的思路查查。这个issue我先关闭了。

**Comment by easythd** [comment]
报告一下，经过把所有相关文件夹手工删除，再重装插件，恢复正常了。

**Comment by alexhua** [comment]
> 报告一下，经过把所有相关文件夹手工删除，再重装插件，恢复正常了。之前应该是删除时漏了一个文件夹。

OK
