### ISSUE TITLE
拦截下载为什么失效了？

### ISSUE THREAD

**Issue by feeshy** [alexhua/Aria2-Explorer#189]
**Describe the bug**

请求检查网站拦截规则中白名单与黑名单的优先级

**To Reproduce**

启用下载拦截

网站白名单填写 `github.com`
网站黑名单填写 `*`

示例文件1 `https://github.com/alexhua/Aria2-Explorer/releases/download/v2.4.1/aria2e-v2.4.1.crx`
示例文件2 `https://music.163.com/song/media/outer/url?id=25640409.mp3`

**Expected behavior**
如果按照白名单优先的规则，预期效果是：拦截文件1，不拦截文件2

**Screenshots**
实际发生的效果：两个文件都不拦截

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: MS Edge
 - Version: 2.4.0

**Comment by alexhua** [comment]
不是优先级的问题，v2.4.0以及之前的版本有个bug会影响拦截效果。
试试 v2.4.1， 看看还有这个问题吗？

**Comment by feeshy** [comment]
感谢
2.4.0重新开关下载拦截已经恢复
2.4.1没出现这个问题
