### ISSUE TITLE
导出成功下载通知次数缺失

### ISSUE THREAD

**Issue by cccqcccq** [alexhua/Aria2-Explorer#191]
win10使用的是2.4.1版本搭配motrix，在拦截成功后会成功弹出一次开始下载的win10通知
![image](https://github.com/alexhua/Aria2-Explorer/assets/117553354/1f0fab9e-0bc5-4e4e-b29b-85b25a236f5b)
当通知中已经有了一次导出成功的提示之后，再次从浏览器下载就不会提示了，必须点击清除所有通知之后再次下载才会提示一次
![1711559496755](https://github.com/alexhua/Aria2-Explorer/assets/117553354/f0d66825-17c9-4c25-aeca-1a80ded1673f)
但是开启检测状态后，每次下载成功都可以成功提示，由于导出下载没有提示会需要打开mortix查看下载列表，希望可以修复这个问题
![1711559583375](https://github.com/alexhua/Aria2-Explorer/assets/117553354/c2af3f9c-6723-45d3-89fb-e0880967416b)

**Comment by alexhua** [comment]
可以在系统通知设置里把 **Chrome / Edge** 的 **在通知中心显示通知** 关掉，只保留 **显示通知横幅** 来缓解一下。
下个版本会做调整，感谢反馈。

**Comment by cccqcccq** [comment]
感谢，目前来说已经够用了！
