### ISSUE TITLE
Onedrive 下载异常

### ISSUE THREAD

**Issue by caite425** [alexhua/Aria2-Explorer#195]
作者您好，似乎是从2.4.1开始，onedrive就无法拦截了，目前更新到了2.4.2也是如此
 
如下截图，现在拦截下载下来的文件都是40KB的无效文件。使用chrome可以正常下载
 
![QQ截图20240426100908](https://github.com/alexhua/Aria2-Explorer/assets/98703352/a533b06b-9266-4c9d-8f77-da1062f2e542)
源文件
![image](https://github.com/alexhua/Aria2-Explorer/assets/98703352/38120209-a251-47f0-a8ca-5c6053e9b367)
实际上这个文件有172MB
辛苦了！

**Comment by alexhua** [comment]
#59
无法复现

**Comment by alexhua** [comment]
如果有详细的复现步骤，欢迎再来反馈。
