### ISSUE TITLE
Put AriaNG e to separate repository

### ISSUE THREAD

**Issue by xearonet** [alexhua/Aria2-Explorer#196]
**Motivation**
Hi Alex.
Your enhanced AriaNG version is awesome. If you could bring us this version in separate repository it will be super useful. I want to use this in my docker image so would be super convenient to have simple github repository with release (i.e. zip file) as single archive. Maybe it helps in development process also. Please consider that. Thanks

**Comment by alexhua** [comment]
It's our core proprietary right now. Maybe I will public the repo in the future. ( Users > 1M ？😀)
