### ISSUE TITLE
文件分类保存的教程没用

### ISSUE THREAD

**Issue by Haerbin23456** [alexhua/Aria2-Explorer#197]
![image](https://github.com/alexhua/Aria2-Explorer/assets/60066765/a6616ad4-6dbf-4cb8-972e-010c178cf327)
我这样设置的，结果最后都保存到了Downloads里

![image](https://github.com/alexhua/Aria2-Explorer/assets/60066765/b1d9e864-f98f-44fe-97e2-675e9ec14ee8)
这里也只有一个选项的说

**Comment by alexhua** [comment]
打开`下载前询问详细参数`，这些设置就不起作用了，这时需要你手动输入下载位置。
