### ISSUE TITLE
若浏览器默认的缩放尺寸超过120%，Aria2-Explorer扩展弹窗的网页尺寸会超出小窗口的尺寸。

### ISSUE THREAD

**Issue by Gokou-Ruri** [alexhua/Aria2-Explorer#198]
浏览器默认的缩放尺寸设置得越大，弹窗内的网页尺寸就越大，就会导致网页超出小窗口的面积，造成操作上的不方便。

![image](https://github.com/alexhua/Aria2-Explorer/assets/26711804/0347b377-edf7-48d2-bf72-908a84fef946)

![image](https://github.com/alexhua/Aria2-Explorer/assets/26711804/8a39bf59-0db0-46c1-ae22-25a3cd4241dc)

**Comment by alexhua** [comment]
这个没有很好的解决方法，扩展没法单独控制缩放比例。

可以试着降低`扩展选项页面` 的缩放比例，125%的比例下这个问题会得到轻微缓解。
