### ISSUE TITLE
奇怪的现象：--daemon=true 启动aria2，添加 http|https 下载会退出aria2

### ISSUE THREAD

**Issue by clav1cula** [alexhua/Aria2-Explorer#199]
**Describe the bug**
MacOS，通过brew 安装aria2 1.37.0
配置--daemon=true 启动aria2，从浏览器扩展Aria2-Explorer 添加 http|https 下载会退出aria2，添加BT 和Metalink下载正常
配置--daemon=false 启动aria2，没有上面的问题
这是 aria2 的问题，还是浏览器Aria2-Explorer 扩展的问题？

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - aria2: 1.37.0

**Comment by alexhua** [comment]
建议用别的客户端测试一下。
