### ISSUE TITLE
[建议]增加右键导出当前页面中的所有连接(可选)

### ISSUE THREAD

**Issue by Superbia000** [alexhua/Aria2-Explorer#20]
效果跟普通右键导出一样，带Cookies，类似IDM
![1](https://user-images.githubusercontent.com/24918410/68731379-d15a0a00-060a-11ea-8d5a-c384b3184c88.png)
![2](https://user-images.githubusercontent.com/24918410/68731453-1b42f000-060b-11ea-98f7-eb5b27159889.png)

**Comment by alexhua** [comment]
不是很擅长做界面，号召有强烈需求并且动手能力强的G友关注下这个feature。

**Comment by alexhua** [comment]
92def9698a47a1a8bb002b2856ac54d544e57485
