### ISSUE TITLE
匯出任何連結時 一律跳出確認介面

### ISSUE THREAD

**Issue by Mas1000** [alexhua/Aria2-Explorer#203]
已經有看過 #35 和其他的相似的issue串

我知道作者你本身是希望能夠最小化使用者的操作次數
但如果可以的話 還是希望能夠在常規設置裡 添加一個"匯出任何連結時 一律跳出確認介面"的開關選項
讓使用者自行決定要不要下載檔案

![image](https://github.com/user-attachments/assets/f0556576-90a5-4833-a289-d1c902926c38)

有時候想要一併下載多個特定連結的時候
一個一個一個右鍵匯出連結會讓操作變得繁瑣(惱
全局匯出又可能會抓到一些不需要的檔案
可以在下載前先跳出圖中的介面的話 我相信對多數使用者的體驗會是加分的 🙏

**Comment by alexhua** [comment]
扩充的设定页不是有 `匯出前詢問詳細设定`和`自動下載前詢問詳細设定` 两个选项么？

**Comment by Mas1000** [comment]
> 扩充的设定页不是有 `匯出前詢問詳細设定`和`自動下載前詢問詳細设定` 两个选项么，不知道是不是你想要的？

啊有 我看到了 原來還有另一個設定頁面
非常感謝 🙏
