### ISSUE TITLE
Help : configure the extension to connect & Use Motrix automatically for downloads, Motrix is already there in the system tray!

### ISSUE THREAD

**Issue by VineetGa** [alexhua/Aria2-Explorer#205]
As mentioned in the title above. In Windows 10, Motrix is sitting / running in the system tray but the chrome extension ''Aria2 explorer'' does not connect & use the Motrix Download Manager automatically for downloads.
Thanks in advance.

**Comment by alexhua** [comment]
Read the usage in the overview carefully.

https://chromewebstore.google.com/detail/aria2-explorer/mpkodccbngfoacfalldjimigbofkhgjn
