### ISSUE TITLE
内网架设的本地aria2服务器地址被认为是非本地运行的远程Aria2,导致cookies丢失

### ISSUE THREAD

**Issue by Copox** [alexhua/Aria2-Explorer#207]
**Describe the bug**
内网有一台电脑提供aria2服务走http,在该插件填写该aria2内网ip及相应端口的时候,插件认为是非本地运行的远程Aria2,不安全.这样直接导致cookies丢失.
因此,这个aria2的服务认为是远程的吗?

**To Reproduce**
举个例子
1.局域网中有台设备提供了aria2服务 假设是`http://内网ip:6800/jsonrpc`
2.装插件的设备是内网中另外的设备
3.把`http://内网ip:6800/jsonrpc`填进插件,黄色提示不安全
![2024-08-14 225834](https://github.com/user-attachments/assets/a83ead17-d03a-41cc-917c-7bcc00c73701)

**Comment by alexhua** [comment]
考虑到这可能是一个常见问题，再提示一条信息，也可以为自己架设的 Aria2 Server 提供SSL自签证书，提高安全性。
基本上分三步：

1. 生成一套用于服务器验证的SSL证书
2. 配置 **Aria2.conf** 文件，指定公钥和私钥 （Windows必须使用pfx格式证书，单文件同时包含公钥和私钥）
3. 将公钥证书添加到前端所在系统的信任证书根列表里

**Comment by Copox** [comment]
其实可否让用户自行选择未加密协议安全开关呢? 而不是只能退回版本到v2.1.5之前了
