### ISSUE TITLE
部分网站需要在请求头中传递 Cookie 才能正常下载

### ISSUE THREAD

**Issue by toseeu** [alexhua/Aria2-Explorer#210]
举例网站 Gofile.io 
**复现步骤** ：
1. 打开 https://gofile.io/d/4hLPqh
2. F12 获取 cookie
3. 直接点击 Download 下载，会发现下载错误。
4. 在 ”HTTP 设置“ 中添加 “自定义请求头” 如下
![image](https://github.com/user-attachments/assets/c87aaf8e-97b0-4d27-a1c1-ac8beea4e58e)
5. 再次点击 Download，下载正常。
***
**解决方案**：
    下载时传递 cookie

**Comment by alexhua** [comment]
#59

**Comment by toseeu** [comment]
首先这个问题再很多防止盗链接的网盘普遍存在，其次这个下载 Aria2 本身是支持 头文件传递的，对所有网站下载增加 cookie 并不会导致现有可以下载的网站不能下载。正是阅读过 #59 我才提问了这个问题。作者只回复 #59 ，意义不明。 需要传递给 Aria2 进行下载基本是大文件场景。这种情况下打概率是网盘和资源站。 防止盗链接是很正常的想象。当然作为一个免费项目，作者没有义务接受所有的改进意见，只是你这个回复让人很不舒服。

**Comment by toseeu** [comment]
比较合适的方案是允许用户对部分网站的下载进行自定义。而不是想现在的**黑名单**一棍子打死

**Comment by alexhua** [comment]
且不说你贴了一个 AriaNG 原版的图， 整个扩展都没用明白，就来提问题，浪费别人的精力，可不得给你直接关了么，这个issue不再回复了。

**Comment by toseeu** [comment]
首先，截图是我的问题，对不起！这个问题的解决方案是我昨天发现的，在公司突然想到可以反馈改进。所以是远程访问家里的AriaNG截图。实际上和插件的内容一样，所有我才没想到要在公司电脑也安装一份，再进行反馈。
<img width="1910" alt="image" src="https://github.com/user-attachments/assets/09639776-7df0-4d14-ada8-763d2f66f471">
这个问题困扰我一段时间了，我也深知自己不会开发修改，再非必要的情况下不该打扰你。所以我对插件的功能充分研究了，插件带的 webUI 是修改后的，多了全部下载，默认排序规则去掉了按时间排序，也无法设置按时间排序。
针对无法正常下载的网站，可以设置黑名单屏蔽。我在此说明只是不想被误解而已，对你已经不报期望了。我不知道你对这个插件的定位是怎样的。我对这个插件的期望是，完全替代浏览器自带的下载，甚至期望能代替 IDM 。
***
以下是改进建议：
1. **希望传递下载的时候不只是代替手动复制链接到AriaNG**：IDM在安装了浏览器扩展的情况下，下载都不存在问题。而没有安装扩展插件时，复制链接到 IDM 部分链接会无法正常下载，因为 IDM 浏览器扩展不只接管下载，还将 cookie 等信息传递到了 IDM 应用程序上。 我期望的 Aria2 浏览器扩展 不只是代替手动复制链接的操作。还能同时传递 请求头。前述的 cookie 是我只知道 IDM 都有传递 cookie 。由于 IDM 并未开源，还传递了什么无从得知。
2. **希望可以自动分类**：已知使用 Alist 的时候，进行批量下载是能传递 文件结构信息的，也就是说 Aria2 是支持下载到二级目录的，浏览器插件还能针对网站或者文件类型多重规则设置不同的保存路径。
3. **希望作者改版的任务可以按创建时间排序**： 已知原版的 AriaNG 默认排序逻辑是按任务创建时间排序，作者的默认排序逻辑是失败的优先，去掉了原版默认的按任务创建时间排序。某些时候很不方便。
***
另：开源平台大家好好交流，github在国内的网络大环境下，很难打开。某种意义上的筛选用户，所以很难碰到啥也不懂的电子白痴的。我反馈问题的时候只是想反馈关键信息，无意触碰作者逆鳞，再次道歉。对不起！

**Comment by alexhua** [comment]
> 开源平台大家好好交流

 这种issue我一般都懒得回，看在你是来真诚交流的份上，我就再回复一下。

1. 扩展不论是**拦截下载**，还是**导出下载**的时都是带Cookies信息的，除非你的Aria2不在本地。即使不在本地，也只在**拦截下载**的时候不带Cookies信息，而且**扩展选项页**有详细的提示和方法告诉你怎么处理。不按模板填写信息，基本的版本信息也没有。不知道你是怎么用的，至少从你提供的信息，我复现不了你的问题，给人的感觉就是用得不熟。这也是你这样的issue不被重视的主要原因。#59 说得很清楚，不是针对你这一个issue。
2. 关于分类下载，你肯定没看过置顶的 #76，也没搜索过相关issue， 我写了好几个帖子介绍如何实现不同文件自动分类下载到不同的目录，可能有点使用门槛但是基本能满足需求。
3. 关于排序，也只是**全部**这个分类是按状态排序的，因为原版没有**全部**这个分类，没有按状态排序这个需求。你所谓的按时间排序，Aria2 任务信息里没有时间信息，默认排序其实是 Aria2 返回的原始顺序（可能跟创建的顺序有关）。只要是相同的状态，扩展的排序也是按这个自然顺序排序的，对于其他三个分类里的任务，扩展跟AriaNG原版并没有多大差别。你想要按时间排序，点进某个具体分类就是了。

所以一个维护了好几年的项目怎么可能会有那么多明显的问题呢，还没用熟练就上来提问题和各种需求，还都是项目不存在的问题或者已经具有的功能，这样是不是有点草率和不礼貌呢。不过你的态度很真诚，我还是愿意多说几句的，把扩展提供的功能用透了再来提问题和需求也不迟，而且可能会更合理一些。这样维护者也更愿意接受。

免费的开源项目，作者大多没有耐心也没有必要给小白用户提供技术支持。好了你也不用道歉了，如何觉得好用请把这个扩展介绍给身边更多的人，用的人越多，作者会更愿维护更新。

**Comment by toseeu** [comment]
关于排序问题：
作者改版的”已下载/已结束“，刚刚暂停所有因为网络原因中断的任务，会**状态优先**分类。
![recording](https://github.com/user-attachments/assets/01e92d3b-2075-44a4-a40f-80782ff9cfca)
原版的”已下载/已结束“，刚刚暂停所有因为网络原因中断的任务，会**任务创建排序**
![image](https://github.com/user-attachments/assets/7a60fb20-ee19-4172-9374-6a22afc75457)
***
抱歉英文的那条置顶 issue 我没有查看，已经反思了。
从**扩展选项页**看不出来勾选**自动下载前询问参数设置**能传递 Cookie。建议可以加一个**悬停提醒**。
正常人会觉得这个不影响是否传递 Cookie 。

**Comment by alexhua** [comment]
这位仁兄，我在这个项目上花的心思可能是你想象的好几倍。从你的使用记录来看，你还没有体会到或者遗漏了很多细节，先慢慢用吧，我就不解释了，这个issue先到这了。
