### ISSUE TITLE
先赞一个👍，持续维护的小而强悍的工具，新需求1:手动切换默认RPC Server 2：自定义图标颜色

### ISSUE THREAD

**Issue by airfx** [alexhua/Aria2-Explorer#96]
![image](https://user-images.githubusercontent.com/37166707/173274481-29d3b7ca-5466-4085-afbd-a853844325c5.png)
监测Aria2状态是个非常好的功能，随时查看状态。
1、希望可以加一个手动排序，或者一键切换监控，默认是第一项，使用很不方面。
2、Chrome  102.0.5005.115（正式版本） （64 位）貌似改变了些什么变成了这样
![image](https://user-images.githubusercontent.com/37166707/173275256-e72aa352-9509-41ed-97d1-ee0dc853d370.png)
参考油猴：
![image](https://user-images.githubusercontent.com/37166707/173275330-7e1ce750-671c-48fc-b284-b463ddd48f43.png)
徽标颜色是可以自定义的。嗯，就这些了，望采纳哈

**Comment by alexhua** [comment]
感谢反馈。
关于需求1，可以参考 #76 关于URL Pattern的说明，已可以通过设置简单切换。
关于需求2，这个暂时不考虑了。
能够保持小巧强悍且一直维护的秘密就是遵循KISS原则，希望理解，哈哈。

**Comment by happy42779** [comment]
我觉得添加一个手动切换默认服务器的功能对我来说挺有必要，因为我目前主力是笔记本，平常下载的安装包都是放在服务器上的，所以默认rpc到server上的aria2c。有时候下载的东西比较大（10+G)就想直接放到本机上，不然下载好了再通过网络加载到本地也要花时间。刚刚也尝试用export导出到本地aria2c，可是下载不成功，大小只有1kb但本地log显示下载成功。
![image](https://user-images.githubusercontent.com/12154967/211804203-55d7983c-4238-4f72-b3e1-217c3b5b5502.png)

**Comment by alexhua** [comment]
- 手动切换默认服务器的功能是有的。在扩展配置页里有多个RPC Server时，自动拦截默认选第一个。想设置其他的 RPC Server 为默认Server，在对应条目的 `URL Patterns` 里填上 `*` 就行。

- 也可以每次下载的时候手动选择使用哪个RPC Server，方法是：1. 打开扩展选项页，启用扩展的`下载前询问参数设置`选项，2. 打开AriaNG，在`AriaNG设置`里添加上你的其他RPC Server。这样下载前就可以在Aria NG左上角选RPC Server了

- 还有你说的通过右键导出的时候选RPC Server也是一种方法

**Comment by alexhua** [comment]
5b0aed1ecf802a5421c0b3879da8691fbb131ce9
